services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ans_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./apps/api:/app/api
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: fastapi_server
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/ans_db
      FASTAPI_ENV: development
    volumes:
      - ./apps/api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./apps/frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_PORT=5173
    command: npm run dev -- --host 0.0.0.0

volumes:
  pgdata:
